### PR TITLE
Miller

### PR DESCRIPTION
**Pull request by bernster**
My first pull request. Fixed a typo and other stuff I didn't necessarily want in here.

### CODE REVIEW

**Comment by marcmentis** [comment]
@bernster Good job. 
- Changes to home page and gemfile are helpful
- database.yml 
  - Should not be in the .gitignore file. 
  - I would not make the changes to the development environment - (i) It now does not match the development environment in the example_application.yml file. (I know I am being inconsistent as the production environments don't match, but most people don't use the production environment much on their local machines. I think people will just automatically copy the example_application.yml code and get frustrated when it doesn't work in development.)

Please re-commit with the above changes and I will merge into dev

**Comment by bernster** [comment]
My thinking was we should all be using oracle XE instead of sql lite but just in case I would leave it out by putting it in the ignore file (even though that didn't work). I'll change it back to mirror the example file.

**Comment by bernster** [comment]
done. rolled back the ignore and database.yml file.

**Comment by marcmentis** [comment]
@bernster. Two small problems remain to get the miller branch to bundle properly
1. Please place the .project file into gitignore. This has something to do with aptana (?eclipse) and causes the bundle command to fail on machines not running aptana. (It makes Rails look for files and paths that don't exist).
2. Please comment out the second (duplicate) "development" group in the Gemfile for two reasons. (i) The two Oracle gems cannot be bundled on Mac's so having them in both development and production environments causes the bundle command to always fail on Mac's. (ii) You have the rspec gem listed twice. This causes a warning at the moment but will result in an error in the future

**Comment by bernster** [comment]
got it.

**Comment by bernster** [comment]
do I need to remove the .project file from git tracking somehow or does the .gitignore do that?

**Comment by marcmentis** [comment]
Git ignore should do it. If not remove it from tracking it's not a part of the app code. You might want to make that a habit on all your code contributions and apps so it doesn't slip through the cracks in the future and cause problems.

**Comment by bernster** [comment]
Hi Marc, I removed the .project file.

**Pull request merged**
